### ISSUE TITLE
Maven test failure on Windows

### ISSUE THREAD

**Issue by io7m** [io7m/jcanephora#17]
```
Running com.io7m.jcanephora.tests.jogl.JOGLImplementationTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.274 sec <<< FAILURE! - in com.io7m.jcanephora.tests.jogl.JOGLImplementationTest
testTooOld(com.io7m.jcanephora.tests.jogl.JOGLImplementationTest)  Time elapsed: 2.27 sec  <<< ERROR!
com.jogamp.opengl.GLException: Profile GL3 is not available on null, but: [GLProfile[GL2ES1/GL2.sw], GLProfile[GL2ES2/GL2.sw], GLProfile[GL2/GL2.sw], GLProfile[GL2/GL2.sw], GLProfile[GL2GL3/GL2.sw]]
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:991)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1004)
	at com.io7m.jcanephora.tests.jogl.JOGLTestContexts.newGL33Drawable(JOGLTestContexts.java:118)
	at com.io7m.jcanephora.tests.jogl.JOGLImplementationTest.testTooOld(JOGLImplementationTest.java:44)

Running com.io7m.jcanephora.tests.jogl.JOGLPixelTypeTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.269 sec - in com.io7m.jcanephora.tests.jogl.JOGLPixelTypeTest
Running com.io7m.jcanephora.tests.jogl.JOGLPolygonModesTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.534 sec <<< FAILURE! - in com.io7m.jcanephora.tests.jogl.JOGLPolygonModesTest
testIdentities(com.io7m.jcanephora.tests.jogl.JOGLPolygonModesTest)  Time elapsed: 1.522 sec  <<< ERROR!
com.jogamp.opengl.GLException: Profile GL3 is not available on null, but: [GLProfile[GL2ES1/GL2.sw], GLProfile[GL2ES2/GL2.sw], GLProfile[GL2/GL2.sw], GLProfile[GL2/GL2.sw], GLProfile[GL2GL3/GL2.sw]]
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:991)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1004)
	at com.io7m.jcanephora.tests.jogl.JOGLTestContexts.newGL33Drawable(JOGLTestContexts.java:118)
	at com.io7m.jcanephora.tests.jogl.JOGLTestContexts.newGL33ContextWithSupplierAndErrors(JOGLTestContexts.java:101)
	at com.io7m.jcanephora.tests.jogl.JOGLTestContexts.newGL33ContextWithSupplier(JOGLTestContexts.java:87)
	at com.io7m.jcanephora.tests.jogl.JOGLTestContexts.newGL33Context(JOGLTestContexts.java:73)
	at com.io7m.jcanephora.tests.jogl.JOGLPolygonModesTest.getPolygonModes(JOGLPolygonModesTest.java:27)
```

It's not clear why these two tests fail consistently. It does not happen when the same tests are executed from an IDE, and does not happen when *all* tests are executed from an IDE.

**Comment by io7m** [comment]
Impressively, this appears to be completely unrelated to test order too: Running with a random ordering still causes those two tests to fail.

**Comment by io7m** [comment]
This is a Cygwin issue!

When Maven is executed from cmd.exe, everything is fine.
